# Generated by Django 5.2 on 2025-04-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='sale',
        ),
    ]
