# Generated by Django 5.2 on 2025-04-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_bankoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankoperation',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
